name: ${name}
version: ${project.version}
main: ${mainClass}
author: royalkingkb
api-version: 1.16
commands:
  banmap:
    permission: ruinscraft.mapban
  unbanmap:
    permission: ruinscraft.mapban
  tpmap:
    permission: ruinscraft.mapban
  similarmaps:
    permission: ruinscraft.mapban
